export enum Messages {
  BOOT_UP_SERVER = 'BOOT_UP_SERVER',
  BOOT_UP_SERVER_SUCCESS = 'BOOT_UP_SERVER_SUCCESS',
  BOOT_UP_SERVER_FAILED = 'BOOT_UP_SERVER_FAILED',
  UPDATE_CHAT_STATE = 'UPDATE_CHAT_STATE',
}
