export enum Messages {
  BOOT_UP_SERVER = 'BOOT_UP_SERVER',
  BOOT_UP_SERVER_SUCCESS = 'BOOT_UP_SERVER_SUCCESS',
  BOOT_UP_SERVER_FAILED = 'BOOT_UP_SERVER_FAILED',
  LOUNGE_CHAT_ADD_MESSAGE = 'LOUNGE_CHAT_ADD_MESSAGE',
  LOUNGE_CHAT_UPDATE_CHAT_STATE = 'LOUNGE_CHAT_UPDATE_CHAT_STATE',
}
